global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']  # Node Exporter

  - job_name: 'zecko-app'
    metrics_path: '/api/admin/metrics'
    static_configs:
      - targets: ['localhost:5000']  # Our Express application

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus itself
